name: CD - Build docker images on pushes to main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version-file: .java-version
          distribution: temurin
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build, test and package
        env:
          # Github Workflows støtter ikke token med read:packages på organisasjonsnivå for maven-pakker,
          # derfor må vi bruke et personlig access token med tilgang til read:packages på organisasjonsnivå
          # https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages
          GITHUB_TOKEN: ${{ secrets.CR_READ_PAT }}
        run: ./gradlew build --no-daemon

      - name: Login to ghcr.io/domstolene
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/domstolene
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build lastest docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/domstolene/<repository-name>:main
